import fs from 'node:fs';
import path from 'node:path';
const V10 = 'v10/fix_01';
const rd = f => fs.existsSync(f) ? JSON.parse(fs.readFileSync(f, 'utf8')) : null;
const t1 = rd(path.join(V10, 'T10-01_corrected_report.json'));
const t2 = rd(path.join(V10, 'T10-02_summary.json')) ?? rd(path.join(V10, 'dataset_v10_manifest.json'));
const t3 = rd(path.join(V10, 'dagger_controlled_report.json'));
const t4p = rd(path.join(V10, 'turn_search_profile.json'));
const t4c = rd(path.join(V10, 'search_comparison.json'));
const t5 = rd(path.join(V10, 'representation_ablation.json'));
const t6 = rd(path.join(V10, 'value_calibration.json'));
const gate = rd(path.join(V10, 'value_gate.json'));
const t7 = rd(path.join(V10, 'expert_iteration_round1.json'));
const t8 = rd(path.join(V10, 'confirmation_results.json'));
const status = {};
status.T1001 = t1 ? 'corrected analysis complete; large confirmation NOT_RUN' : 'missing';
status.T1002 = (t2?.accounting?.naturalTerminalEpisodes >= 100 && t2?.accounting?.uniqueStateCount > 0 && t2?.accounting?.replayErrors === 0) ? 'complete (real split, replay, unique-state accounting)' : 'partial';
status.T1003 = t3?.consumptionAudit?.invariantPassed ? (t3.findings?.deltaArmC_vs_ArmB_naturalWinRate > 0 ? 'complete: verified development gain' : 'complete: no verified gain (honest)') : 'invalid/not run';
status.T1004 = t4c?.status ? 'partial: ' + t4c.status : (t4p ? 'partial: fixtures only' : 'not run');
status.T1005 = t5?.representationArms ? 'complete: real 3-arm ablation (no winner declared)' : 'not run';
status.T1006 = gate ? (gate.valueHeadQualified ? 'complete: value qualified' : 'complete: value not qualified, downstream blocked') : 'not run';
status.T1007 = t7?.status ?? 'not run';
status.T1008 = t8?.status ?? 'not run';
const lines = [];
lines.push('# V10 fix_01 执行总结');
lines.push('');
lines.push('生成时间：' + new Date().toISOString());
lines.push('Run ID：agent_upgrade_20260923_v10_fix_01');
lines.push('');
lines.push('## 任务状态');
for (const [k, v] of Object.entries(status)) lines.push('- ' + k + ': ' + v);
lines.push('');
lines.push('## 关键实测');
if (t1) lines.push('- T10-01: pure newBest W/(W+L)=' + t1.purePolicyFinding?.newBest?.naturalWinRate + '% vs old=' + t1.purePolicyFinding?.oldModel?.naturalWinRate + '%; S10=' + t1.searchFinding?.s10?.naturalWinRate + '% vs S00=' + t1.searchFinding?.s00?.naturalWinRate + '%.');
if (t2) lines.push('- T10-02: episodes=' + t2.accounting?.scenarioAttemptCount + ', natural=' + t2.accounting?.naturalTerminalEpisodes + ', uniqueStates=' + t2.accounting?.uniqueStateCount + ', trainRoots=' + t2.splits?.train?.rootFamilyCount + ', valIdRoots=' + t2.splits?.val_id?.rootFamilyCount + ', valOodRoots=' + t2.splits?.val_ood?.rootFamilyCount + ', testRoots=' + t2.splits?.test?.rootFamilyCount + '.');
if (t3) lines.push('- T10-03: A/B/C natural W/(W+L)=' + t3.evaluationResults?.armA_baseline?.naturalWinRate + '% / ' + t3.evaluationResults?.armB_control?.naturalWinRate + '% / ' + t3.evaluationResults?.armC_dagger?.naturalWinRate + '%; C consumed new=' + t3.consumptionAudit?.consumedNewIds + '/' + t3.consumptionAudit?.newSampleIds + '.');
if (t5) lines.push('- T10-05: Arm1/2/3 OOD=' + t5.representationArms?.['t10-05-arm1-2block']?.valOodAcc + '% / ' + t5.representationArms?.['t10-05-arm2-2block-gap']?.valOodAcc + '% / ' + t5.representationArms?.['t10-05-arm3-4block']?.valOodAcc + '%; Arm2 GAP implemented.');
if (t6) lines.push('- T10-06: valueHeadQualified=' + t6.qualificationAudit?.valueHeadQualified + '; Arm2 pearson=' + t6.calibrationComparison?.arm2_value_weight_01?.pearsonCorrelation + ', MSE=' + t6.calibrationComparison?.arm2_value_weight_01?.overallMse + '.');
if (t7) lines.push('- T10-07: ' + t7.status + ' ' + ((t7.reasons ?? []).join('; ')));
lines.push('');
lines.push('## 未完成/阻塞');
lines.push('- T10-01 large same-protocol confirmation NOT_RUN; only "no verified strength improvement" is claimed.');
lines.push('- T10-04 formal 80-match equal-work comparison remains partial; real fixtures + current smoke comparison only.');
lines.push('- T10-07/T10-08 blocked by conditional dependencies and P0 results, correctly NOT_RUN.');
lines.push('');
lines.push('## 产物');
for (const f of fs.readdirSync(V10).sort()) if (f.endsWith('.json') || f.endsWith('.md')) lines.push('- v10/fix_01/' + f);
fs.writeFileSync(path.join(V10, 'V10_FIX_01_SUMMARY.md'), lines.join('\n'), 'utf8');
fs.writeFileSync(path.join(V10, 'tasks_v10_fix_01.json'), JSON.stringify({ runId: 'agent_upgrade_20260923_v10_fix_01', generatedAt: new Date().toISOString(), statuses: status }, null, 2), 'utf8');
console.log('[summary]', JSON.stringify(status));
